
# Baseline characteristics tables

```{r results = 'asis', include = TRUE}
tableby(CDX_Cog ~ Age + Ethnicity + ID_Hispanic + ID_Race_White + ID_Race_Black + 
    ID_Race_IndianAlaska + ID_Race_Asian + ID_Race_NativeHawaiian + ID_Gender + 
    Interview_Language + ID_Language_Primary + ADI_StateRank + 
    MMSE_Total + Digit_Symbol_Substitution + SEVLT_DR_Total + LM2_AB_Total + Animal_Total + 
    APOE4_Genotype + APOE4_Positivity + `01_AB_FBB_AB_pos` + 
    `01_TAU_PI2620_Medial_Temporal_SUVR` + `01_L_hippocampus` + `01_R_hippocampus` + 
     HPACC, 
  data = HD_subjinfo) %>%
  summary(labelTranslations = HD_labels, digits = 1)

tableby(Ethnicity ~ CDX_Cog + Age + ID_Hispanic + ID_Race_White + ID_Race_Black + 
    ID_Race_IndianAlaska + ID_Race_Asian + ID_Race_NativeHawaiian + ID_Gender + 
    Interview_Language + ID_Language_Primary + ADI_StateRank + 
    MMSE_Total + Digit_Symbol_Substitution + SEVLT_DR_Total + LM2_AB_Total + Animal_Total + 
    APOE4_Genotype + APOE4_Positivity + `01_AB_FBB_AB_pos` + 
    `01_TAU_PI2620_Medial_Temporal_SUVR` + `01_L_hippocampus` + `01_R_hippocampus` + 
     HPACC, 
  data = HD_subjinfo) %>%
  summary(labelTranslations = HD_labels, digits = 1)
```

# Summary plots

```{r habs-spaghetti, fig.cap='Spaghetti of selected outcomes by age and ethnicity.'}
HD_Imaging %>% 
  select(-Ethnicity) %>%
  left_join(HD_Clinical, by = c('Med_ID', 'Visit_ID', 'Age')) %>%
  mutate(Hippocampus = `01_L_hippocampus` + `01_R_hippocampus`) %>%
  select(Med_ID, Age, Ethnicity, `01_AB_FBB_Global_SUVR`, 
    `01_TAU_PI2620_Medial_Temporal_SUVR`, Hippocampus, 
    `02_WMH_Volume_Log`, HPACC) %>%
  pivot_longer(`01_AB_FBB_Global_SUVR`:HPACC) %>%
ggplot(aes(x=Age, y=value, color=Ethnicity)) +
  geom_point(alpha=0.1) +
  geom_line(aes(group = Med_ID), alpha=0.1) +
  facet_wrap(vars(name), scales = 'free_y') +
  guides(colour = guide_legend(override.aes = list(alpha=1)))
```

```{r habs-loess, fig.cap='Locally weighted scatterplot smooths (LOWESS) of selected outcomes by age and ethnicity.'}
HD_Imaging %>% 
  select(-Ethnicity) %>%
  left_join(HD_Clinical, by = c('Med_ID', 'Visit_ID', 'Age')) %>%
  mutate(Hippocampus = `01_L_hippocampus` + `01_R_hippocampus`) %>%
  select(Med_ID, Age, Ethnicity, `01_AB_FBB_Global_SUVR`, 
    `01_TAU_PI2620_Medial_Temporal_SUVR`, Hippocampus, 
    `02_WMH_Volume_Log`, HPACC) %>%
  pivot_longer(`01_AB_FBB_Global_SUVR`:HPACC) %>%
ggplot(aes(x=Age, y=value, color=Ethnicity)) +
  geom_smooth(method = 'loess') +
  geom_rug(alpha = 0.1) +
  facet_wrap(vars(name), scales = 'free_y') +
  guides(colour = guide_legend(override.aes = list(alpha=1)))
```
